### ISSUE TITLE
No eraser on PC

### ISSUE THREAD

**Issue by Soba77** [setpixel/storyboarder#1]
Eraser doesn't work on PC. 

- Eraser end of pen doesn't work.

- Eraser button on tool bar doesn't  switch pen function, from draw to erase

**Comment by Soba77** [comment]
Okay, Discover left click enables eraser

**Comment by setpixel** [comment]
This is a bug in chrome. They say they will fix soon.

In the meantime, you can map the eraser to right click for storyboarder specifically in the wacom utility.
