### ISSUE TITLE
"Undo" doesn't retain history per board

### ISSUE THREAD

**Issue by Soba77** [setpixel/storyboarder#2]
Working on a scene (Sce. 17). Hit a wall, so went on to a different scene (Sce. 20).
When i came back to the previous scene (Sce. 17), I wanted to "undo" some of the lines i did earlier...
Canvas image would then show the "undo"  being done to the last scene i worked on (Sce.20).  This Sce 20 image was now copied to Sce 17, replacing the original Sce 17 image i was trying to undo
![scrshot_undoissueonpc](https://cloud.githubusercontent.com/assets/14130545/22340819/bbe1516a-e3bc-11e6-83b8-45d24cf790de.jpg)

**Comment by setpixel** [comment]
I'm redoing the undo system to be image specific, layer specific, scene specific. So if you go to a scene, add a new image, make some changes,... you can undo it all in steps.

**Comment by setpixel** [comment]
Merging into #27
