### ISSUE TITLE
Canvas kept appearing blank

### ISSUE THREAD

**Issue by Soba77** [setpixel/storyboarder#24]
I had to restart the app a few time due to the canvas appearing blank, the thumbs too.

NOTE: The issue may have to do with Github, when restarting didn't work, even after i committed; I only clicked on Github app window, and it refreshed.

**Comment by setpixel** [comment]
Can you reliably recreate this? Also how often does it happen?

**Comment by setpixel** [comment]
Merged same issue into #15

**Comment by Soba77** [comment]
Yes this happens all time for me. not sure its  just cause it my computer. It also has been taking longer to load the thumbs. i can see the thumbs rendering line by line

**Comment by setpixel** [comment]
Can you trigger this reliably? Can you make it happen?

**Comment by setpixel** [comment]
Note: attempt to test with usb drive for slow driver performance.
