### ISSUE TITLE
Hook up UI buttons

### ISSUE THREAD

**Issue by setpixel** [setpixel/storyboarder#35]

**Comment by audionerd** [comment]
Toolbar buttons are now connected to the UI (for features that are available).

**Comment by setpixel** [comment]
We still need to hook up the playback buttons

**Comment by audionerd** [comment]
Transport:
- remove keyboard control (spacebar) of play button
- no sound on/off
- no loop

**Comment by audionerd** [comment]
- [ ] Setup "Caption" toggle in Toolbar
