### ISSUE TITLE
Huion Tablet support

### ISSUE THREAD

**Issue by CuberToy** [setpixel/storyboarder#43]
Well everything is in the title, I think.
Driver is not supported, I believe, so no pressure and lots of jitter.

**Comment by setpixel** [comment]
Ah - could you record a screen capture video of 20 seconds or so of drawing? If it's too much of a pain, no problem. Or - even a close up camera phone video. I just want to see the jitter.

Currently, windows is waiting on pen support inside of chromium, they say they are working on it. Should be done in the next 2 months.

Regarding jitter, I want to see the behavior. I have a MS Surface and I see it as well, but it isn't horrible. My plan is to artificially line smooth (which I think most windows apps do)

**Comment by CuberToy** [comment]
Here's the video : https://drive.google.com/open?id=0B_duL9AEjIplblZZcTlFbXptaFk
(may take a a few second for it to be processed, 'cause it has to be seen in HD )

As you can see, it's not horrible either, just there. I had read about the chromium support, should have thought of that.

Thanks for fast reply.

**Comment by setpixel** [comment]
Got it! Yeah, its the same as the MS Surface. 

What is the model number of the HUION Tablet? I might be able to test it.

**Comment by CuberToy** [comment]
I have an "old" H610 (not pro or anything).
But the drivers are pretty much the same as the newest.

**Comment by setpixel** [comment]
Ok! Will try to get a H610 to test. Thanks!

Merging this issue in #38
