### ISSUE TITLE
Multiple "issues"

### ISSUE THREAD

**Issue by CuberToy** [setpixel/storyboarder#45]
Feel free to delete this after if I'm wrong.
I'm not sure if it's an issue or intended (as, "not yet in there").
- Buttons in toolbar does nothing
- No Undo/Redo

Again, maybe not an issue (since it seems I'm the only one, it may be totally normal and I just forgot to read one line correctly).

Run on Win10

**Comment by setpixel** [comment]
Thanks for the issues, 

Keep them coming! And ideas are welcome too!

buttons do nothing: #35 
undo (working on it today :D): #27 

This is the order I'm working on things for the beta release.
