### ISSUE TITLE
Script editing (existing script in right panel)

### ISSUE THREAD

**Issue by garyritchie** [setpixel/storyboarder#63]
Looking for clarification on the UI. From my perspective, I was expecting to be able to edit Dialog, Action and Notes from my original/imported fountain script. Or is the intent for the right panel for new data only? I could see a situation where you would import a draft script and board it while refining the dialog/action, etc.

![10_027script](https://cloud.githubusercontent.com/assets/853094/23320026/1422a26a-faa7-11e6-8393-b7d526580baa.png)

**Comment by setpixel** [comment]
Hi Gary,

We wanted to take the stance that Storyboarder should be non-destructive to the script. 

When we've been using storyboard fountain to board, we ended up hating how locked to the script it was. We wanted to use the script as a guide and go back to the script to reconcile it later. 

Storyboarding shouldn't modify the script. 

But! Totally want to hear what you think about that. Would love to have a discussion here.

**Comment by garyritchie** [comment]
Hey Charles, I respect your focus, and I remember reading that I can simply open my script in an editor. There's a challenge, though: indicating to the user, _when_ that right panel area is used. Perhaps only when there isn't a script supplied when starting Storyboarder? 

I'm drawing, though, so, I'm all smiles. I think you have something really nice here (I also enjoyed your first iteration on a previous project). Hope I can help in some way in the future.

**Comment by setpixel** [comment]
Yes... In the near term, I want to link that text to an external editor. (I wish I could link to an external editor to a specific line!) I see you're using linux. Thats really interesting!

**Comment by garyritchie** [comment]
Re: external editor -- I'd like to be able to change that in a preference dialog or text file. I use Krita for most pixel pushing here.

Yeah, Ubuntu 16.04 with i3 window manager. It's an aging desktop with a new nvidia consumer-grade (4GB) gaming card. Just got my dongle so I can use the cintiq with an old laptop (1GB AMD) dual-booting the same with Win10. Most of my feedback will probably come from the linux desktop.

I like the "low overhead" keyboard commands. I never touch the tools now (I think most of them don't work?). The key commands help make boarding _fast_.

**Comment by setpixel** [comment]
working on this now: https://www.dropbox.com/s/6iqg5sl691dskep/Screenshot%202017-02-24%2016.04.41.png?dl=0

**Comment by garyritchie** [comment]
I like your MO. "Fuck up, bruh?" Is that going to be a UI tour or when mouseover? I'm lazy, so I would have just put it on a screen behind F1 and CTRL+?.

I like your tool icons, but I want to _kill_ the styling on the group containers.... Just an opinion. If I can get a moment... wait... fuck, I know this! ...Anyway, I'm trying to get through a project. Afterward I might try to send you an awful pull request. Don't have Electron experience, but I've been designing/building for web for some time.

This is a start:

```css
#toolbar .group {
    /* background-color: #444; */
    float: left;
    /* border-radius: 8px; */
    margin-left: 10px;
    /* padding: 6px; */
    /* box-shadow: inset 0 -4px 0px rgba(0,0,0,0.2), inset 0 1px 1px rgba(255,255,255,0.2), 0 2px 2px rgba(0,0,0,0.3); */
    border-right: 1px solid grey;
}
```

**Comment by garyritchie** [comment]
Something along those lines will better support your existing aesthetic, I think.

This is my second project using your work. When I get my boards done I'll drop them into my rough edit. Not sure how that's gonna go just yet, but I like that there's real images in the storyboards folder.

**Comment by setpixel** [comment]
![screenshot 2017-02-26 14 24 17](https://cloud.githubusercontent.com/assets/441117/23342843/4a49a364-fc2f-11e6-8908-381227d0c529.png)

what do you think of this?

**Comment by garyritchie** [comment]
I really like it! The fourth tool in looks like a paintbrush. Perhaps making the bristle portion curl to the left or right would break the symmetry and help it look more brush-like.

**Comment by setpixel** [comment]
![image](https://cloud.githubusercontent.com/assets/441117/23343754/64066486-fc3e-11e6-9df9-63e2335cca71.png)

**Comment by garyritchie** [comment]
Yup!

**Comment by garyritchie** [comment]
Left this tab open, so when I saw the pencils again while a bit blurry-eyed, I though they could use a little tweaking...

![64066486-fc3e-11e6-9df9-63e2335cca71_pencils](https://cloud.githubusercontent.com/assets/853094/23364746/4f697d3e-fcce-11e6-9b40-6db9632f6580.png)

I'm sure I broke the visual rhythm you had going there but I wanted the two pencils on the left to look a little more different.

**Comment by setpixel** [comment]
Will think about script editing.. but for now, will not mutate script.
