### ISSUE TITLE
User can swap a board left/right (AKA 're-order')

### ISSUE THREAD

**Issue by audionerd** [setpixel/storyboarder#72]
User can swap board order
The user can invoke this command via
- Context Menu
- Keyboard command, or 
- Menu Bar

Swap can happen on a single current board OR on a multiselection.

For single board:
```
SWAP LEFT
[A, B, *C*, D, E] Given Current Board is C at zero-indexed position 2
[A, *C*, B, D, E] Swap Left will exchange B and C. Prior current board remains active.

SWAP RIGHT
[A, B, *C*, D, E] Given Current Board is C at zero-indexed position 2
[A, B, D, *C*, E] Swap Right will exchange C and D. Prior current board remains active.
```

For multi-selection:
```
SWAP LEFT:
[A, B, *C, D, E*, F, G] 
[A, *C, D, E*, B, F, G] 

SWAP RIGHT:
[A, B, *C, D, E*, F, G] 
[A, B, F, *C, D, E*, G] 
```

Prevent extending beyond bounds

**Comment by setpixel** [comment]
Multiselect:

SWAP LEFT:
[A, B, *C, D, E*, F, G] 
[A, *C, D, E*, B, F, G] 

[A, B, *C, D, E*, F, G] 
[A, B, F, *C, D, E*, G] 

It should maintain the selection and change the index though IMO.

**Comment by audionerd** [comment]
Cool. Updated in Issue desc.

**Comment by audionerd** [comment]
In progress on `reordering` branch.
