### ISSUE TITLE
Create a color picker based on material color palette 

### ISSUE THREAD

**Issue by setpixel** [setpixel/storyboarder#73]
- [x] set z-index proper
- [x] set cursor to normal
- [x] make bottom color black
- [x] update color name on hover
- [x] find the closest color - update active
- [x] click to set active color
- [x] emit active color
- [x] round corners of colors on edges
- [x] responsive smaller for smaller screens

**Comment by audionerd** [comment]
color picker is connected to toolbar now in `master`
