### ISSUE TITLE
show aspirational message on launch and every hour of boarding

### ISSUE THREAD

**Issue by setpixel** [setpixel/storyboarder#77]
load messages from url

**Comment by audionerd** [comment]
Sounds like maybe Growl-style? But animating upward from the bottom right of the screen?

http://ksylvest.github.io/jquery-growl/
https://notifyjs.com/

**Comment by setpixel** [comment]
Yeah!

**Comment by setpixel** [comment]
Ideas for content to add:

- Quotes
- Jokes
- Fortune cookie messages .. in bed.
- Did you know?: Interesting fake facts
- Story prompts
- Office gossip

**Comment by audionerd** [comment]
Notification system and randomized quotes are in `master` now.
